---
work_path: ./work
log_level: DEBUG
# release_uri: gs://open-targets-pre-data-releases/jferrer/test-pts-pyspark
pool: 8
efo_version: v3.81.0

steps:
  #: DISEASE STEP :#################################################################################
  disease:
    - name: transform disease_efo
      source: input/disease/efo_otar_slim.json
      destination: output/disease/disease.parquet
      transformer: disease
    - name: transform disease_hpo
      source: input/disease/hp-full.json
      destination: output/disease_hpo/disease_hpo.parquet
      transformer: disease_hpo
    - name: transform disease_phenotype
      requires:
        - transform disease_efo
      source:
        - output/disease/disease.parquet
        - input/disease/phenotype.hpoa
        - input/disease/mondo.json
      destination: output/disease_phenotype/disease_phenotype.parquet
      transformer: disease_phenotype
    - name: transform disease_efo for webapp
      requires:
        - transform disease_efo
      source: output/disease/disease.parquet
      destination: webapp/disease.jsonl
      transformer: disease_efo_webapp

  ##################################################################################################

  #: EXPRESSION STEP :##############################################################################
  expression:
    - name: unzip normal tissue
      source: input/expression/normal_tissue.tsv.zip
      destination: intermediate/expression/normal_tissue.tsv
    - name: gzip normal tissue
      requires:
        - unzip normal tissue
      source: intermediate/expression/normal_tissue.tsv
      destination: intermediate/expression/normal_tissue.tsv.gz

    - name: transform expression tissue
      source: input/expression/map_with_efos.json
      destination: intermediate/expression/tissue-translation-map.parquet
      transformer: expression_tissue
  ##################################################################################################

  #: MOUSE_PHENOTYPES STEP :########################################################################
  mouse_phenotype:
    - name: pyspark separate into output and excluded
      source:
        target: output/target
        mouse_phenotype: input/mouse_phenotype/mouse_phenotypes.json.gz
      destination:
        output: output/mouse_phenotype
        excluded: excluded/mouse_phenotype
      pyspark: mouse_phenotype

  ##################################################################################################

  #: OPENFDA STEP :#################################################################################
  openfda:
    - name: explode_glob transform openfda drug events
      glob: input/openfda/**/*.zip
      do:
        - name: transform ${match_path}${match_stem}
          source: ${match_prefix}/${match_path}${match_stem}.${match_ext}
          destination: intermediate/openfda/${uuid}.parquet
          transformer: openfda
  ##################################################################################################

  #: SO STEP :######################################################################################
  so:
    - name: transform so
      source: input/so/so.json
      destination: output/so/so.parquet
      transformer: so
  ##################################################################################################

  #: TARGET STEP :##################################################################################
  target:
    - name: unzip subcellular location
      source: input/target/hpa/subcellular_location.tsv.zip
      destination: intermediate/target/hpa/subcellular_location.tsv
    - name: gzip subcellular location
      requires:
        - unzip subcellular location
      source: intermediate/target/hpa/subcellular_location.tsv
      destination: intermediate/target/hpa/subcellular_location.tsv.gz

    - name: csv_to_parquet subcellular location ssl
      source: input/target/hpa/subcellular_locations_ssl.tsv
      destination: intermediate/target/hpa/subcellular_locations_ssl.parquet
      separator: "\t"

    - name: unzip essentiality matrix
      source: input/target/project-scores/essentiality_matrices.zip
      inner_file: EssentialityMatrices/04_binaryDepScores.tsv
      destination: intermediate/target/project-scores/04_binaryDepScores.tsv
    - name: csv_to_parquet essentiality matrix
      requires:
        - unzip essentiality matrix
      source: intermediate/target/project-scores/04_binaryDepScores.tsv
      destination: intermediate/target/project-scores/04_binaryDepScores.parquet
      separator: "\t"

    - name: csv_to_parquet gene identifier
      source: input/target/project-scores/gene_identifiers_latest.csv.gz
      destination: intermediate/target/project-scores/gene_identifiers_latest.parquet

    - name: transform ensembl
      source: input/target/ensembl/homo_sapiens.json
      destination: intermediate/target/ensembl/homo_sapiens.parquet
      transformer: ensembl

    - name: transform gnomad
      source: input/target/gnomad/gnomad.v2.1.1.lof_metrics.by_gene.txt.bgz
      destination: intermediate/target/gnomad/gnomad_lof_by_gene.txt.gz
      transformer: gnomad

    - name: explode_glob homology
      glob: input/target/homologue/gene_dictionary/*.json
      do:
        - name: transform ${match_stem} to parquet
          source: ${match_prefix}/${match_path}${match_stem}.${match_ext}
          destination: intermediate/target/homologue/gene_dictionary/${match_path}${match_stem}.parquet
          transformer: homology
  ##################################################################################################

  evidence:
    - name: pyspark clingen
      source:
        evidence: input/evidence/clingen.csv
      destination: intermediate/evidence/clingen.parquet
      properties:
        efo_version: v3.81.0
      pyspark: clingen
